### ISSUE TITLE
Setting the detailed-exitcode option causes the action to report a failure when plans report changes

### ISSUE THREAD

**Issue by Clockwork-Muse** [gruntwork-io/terragrunt-action#102]
**Describe the bug**
When the `-detailed-exitcode` flag is set, the action ends up failing because of the non-zero exit code when plans report changes.

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```
- id: plan
  name: Get terraform plans
  uses: gruntwork-io/terragrunt-action@aee21a7df999be8b471c2a8564c6cd853cb674e1
  with:
    tf_version: 1.12.2
    tg_version: 0.81.10
    tg_dir: ${{ github.workspace }}/terraform/${{ matrix.environment }}
    tg_command: run --all plan --non-interactive -- -detailed-exitcode
```

**Expected behavior**
The action succeeds when there are plan changes (exit code), and only fails when the failure exit code `1` is returned.

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt Action version: 2.1.8
- Environment details (Terragrunt version, Terraform version, etc.):
  - tf_version: 1.12.2
  - tg_version: 0.81.10

**Additional context**
