### ISSUE TITLE
Terragrunt action fails with git config error

### ISSUE THREAD

**Issue by nmklotas** [gruntwork-io/terragrunt-action#15]
**Describe the bug**
Terragrunt github action fails

**To Reproduce**

```
    - name: Plan
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.TF_VERSION }}
          tg_version: ${{ env.TG_VERSION }}
          tg_dir: ${{ env.DEPLOYMENT_DIR }}
          tg_command: "run-all plan"
```

gives output:
```
21:49:29 Starting Terragrunt Action
error: wrong number of arguments, should be 2
usage: git config [<options>]
...
```

**Expected behavior**
Runs successfully

**Versions**
tf_version: 1.5.2
tg_version: 0.48.0
action version: 1.0.6
