### ISSUE TITLE
Install version from `terragrunt_version_constraint`

### ISSUE THREAD

**Issue by Moulick** [gruntwork-io/terragrunt-action#18]
Can we have this action figure out and install terragrunt version from the `terragrunt_version_constraint` in terragrunt.hcl?

**Additional context**
This will help in keeping terragrunt version automatically updated within reason

**Comment by denis256** [comment]
Hello,
looks like to implement this feature will be required to parse HCL files(with includes, locals, env variables resolving) and identify which will be the value of `terragrunt_version_constraint`

**Comment by Moulick** [comment]
As far as I read, `tgswitch` supports figuring out the version `terragrunt_version_constraint` automatically. https://github.com/warrensbox/tgswitch#use-terragrunthcl-file It'll figure out the version from `.terragrunt-version` or `terragrunt_version_constraint` if a version is not explicitly mentioned

**Comment by michw** [comment]
A workaround that works for me:

```
       - name: 'Extract terraform and terragrunt version from terragrunt-root.hcl'
         id: extract-tftg-version
         run: |
           tf_version=$(sed -n 's/^terraform_version_constraint.*=.*\"= \([0-9.]\+\)\"/\1/p' terragrunt-root.hcl)
           tg_version=$(sed -n 's/^terragrunt_version_constraint.*=.*\"= \([0-9.]\+\)\"/\1/p' terragrunt-root.hcl)
           echo "tf_version=$tf_version" | tee -a "$GITHUB_OUTPUT"
           echo "tg_version=$tg_version" | tee -a "$GITHUB_OUTPUT"
```

and then use them, i.e.:

```
       - name: (staging) terragrunt plan
         uses: gruntwork-io/terragrunt-action@v1
         with:
           tf_version: ${{ steps.extract-tftg-version.outputs.tf_version }}
           tg_version: ${{ steps.extract-tftg-version.outputs.tg_version }}
           tg_dir: '${{ github.workspace }}/non-prod/us-east-1/staging'
           tg_command: '--terragrunt-non-interactive run-all plan'
```
