### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by Moulick** [gruntwork-io/terragrunt-action#19]
**Describe the bug**
The action is not commenting on the pull request

**To Reproduce**

```yaml
name: run

on:
  pull_request:
  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the token from STS
  contents: read # This is required for actions/checkout
  pull-requests: write # This is required for writing comments

env:
  AWS_DEFAULT_REGION: eu-central-1
  REPO_NAME: ${{ github.event.repository.name }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws/configure-aws-credentials@v3
        with: <...>

      - name: Terragrunt plan
        uses: gruntwork-io/terragrunt-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tg_comment: true

          tf_version: "1.5.6"
          tg_version: " 0.50.7"
          tg_dir: "envs/preview"
          tg_command: "plan --terragrunt-log-level trace --terragrunt-debug"
        continue-on-error: true
```

**Expected behavior**

The PR should have a comment

**Nice to have**

These are the last log lines of the action
![image](https://github.com/gruntwork-io/terragrunt-action/assets/15780903/7669e55c-34d2-4455-9071-bb1bff6518b9)

**Versions**
- Terragrunt Action version: @v1
- Environment details (Terragrunt version, Terraform version, etc.):
  - tf_version: "1.5.6"
  - tg_version: " 0.50.7"
