### ISSUE TITLE
bug: Host key verification failed.

### ISSUE THREAD

**Issue by nadiia-caspar** [gruntwork-io/terragrunt-action#3]
Hello all,

i got this error when i try to use the action to run Terragrunt code with the source module in the private repo in our Organization. Any ideas what am i misssing?

```
2023-07-06 10:04:20 Starting Terragrunt Action
Installing Terraform v1.4.6
Downloading release tarball from https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_linux_amd64.zip
#=#=#                                                                         

######################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/1.4.6/terraform_1.4.6_SHA256SUMS
Not instructed to use Local PGP (/root/.tfenv/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification
Archive:  /tmp/tfenv_download.huXhbM/terraform_1.4.6_linux_amd64.zip
  inflating: /root/.tfenv/versions/1.4.6/terraform  
Installation of terraform v1.4.6 successful. To make this your default version, run 'tfenv use 1.4.6'
Switching default version to v1.4.6
Default version (when not overridden by .terraform-version or TFENV_TERRAFORM_VERSION) is now: 1.4.6
Terragrunt version environment variable: 0.48.1
2023/07/06 10:04:21 Creating directory for terragrunt: /root/.terragrunt.versions/
Downloading https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.1/terragrunt_linux_amd64 to terragrunt_linux_amd64
Downloading ...
45860175 bytes downloaded.
Switched terragrunt to version "0.48.1" 
time=2023-07-06T10:04:22Z level=error msg=1 error occurred:
	* error downloading 'ssh://git@github.com/<MY_ORG_REPO>.git?ref=CS-18[40](https://github.com/<MY_ORG_REPO>/actions/runs/5474158844/jobs/9968581534?pr=2000#step:9:41)-<MY_BRANCH>': /usr/bin/git exited with 128: Cloning into '/github/workspace/ops/infra/k8s-namespaces/.terragrunt-cache/PsfxNe6tOQxoAt7aLLXD3Lfig4Q/K_Yq5P6N-cJMXT_DsddixApUVIo'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by denis256** [comment]
Hi,
most probably should be passed SSH key to clone private repository

in my projects, I use `webfactory/ssh-agent` action to start SSH agent and pass socket to the action container, basically, steps are next:
  * create SSH key and public key to your GH account or to private repository as deploy key
  * save private key as action secret, I usually save it under `SSH_PRIVATE_KEY` name
  * use `webfactory/ssh-agent` to start SSH agent and use `SSH_PRIVATE_KEY`
  * pass agent socket to Terragrunt action under `SSH_AUTH_SOCK` env variable

Simplified example:
```
...
      - name: create directory to pass ssh-agent socket
        run: "mkdir -p /home/runner/work/_temp/_github_workflow"
        shell: bash

      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: "/home/runner/work/_temp/_github_workflow/ssh-agent.sock"

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v1
        env:
            SSH_AUTH_SOCK: "/github/workflow/ssh-agent.sock"
...
```

Reference:
https://github.com/denis256/tg-gh-action-examples/blob/master/.github/workflows/private-repo.yml#L36
