### ISSUE TITLE
Job runs as `root`

### ISSUE THREAD

**Issue by osher** [gruntwork-io/terragrunt-action#30]
**Describe the bug**
The job runs as `root` - as a result, `.terragrunt-cache` are owned by root.
When future steps run as `runner` - globs, scandir and directory traversing ends with an error.

**To Reproduce**
Try to upload artifacts using the official action after the terragrunt job

```
  run-tg:
    needs: [ detect ]
    if: needs.detect.outputs.TG_TARGETS != '[]'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include: "${{ fromJSON(needs.detect.outputs.TG_TARGETS) }}"

    env:
      TF_VERSION: 1.6.1
      TG_VERSION: 0.52.3

    steps:
      - name:   Checkout code
        uses:   actions/checkout@v4

      - name:   Plan
        id:     tg-plan
        uses:   gruntwork-io/terragrunt-action@v1
        env:
          AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
        with:
          tf_version: ${{ env.TF_VERSION }}
          tg_version: ${{ env.TG_VERSION }}
          tg_dir:     ${{ matrix.ENV_DIR }}
          tg_command: 'run-all plan -out tf.plan'

      - name:   debug
        shell:  bash
        run: |
          echo common/subdomain-rnd/
          ls -la  envs/common/subdomain-rnd/
          whoami

      - name:   save output to file
        shell:  bash
        env:
          TG_PLAN_LOG: ${{join(steps.tg-plan.outputs.*, '\n')}}
        run: echo "${TG_PLAN_LOG//%0A/$'\n'}" > ${{matrix.ENV_DIR}}/tg.plan.log

      - name:   save plan as build artifact
        uses:   actions/upload-artifact@v3
        with:
          name: ${{matrix.NAME}}.tg-plans
          path: |
            ${{matrix.ENV_DIR}}/**/tf.plan
            ${{matrix.ENV_DIR}}/tg.plan.log
            !${{matrix.ENV_DIR}}/**/.terra*
```

**Expected behavior**
The CI should pass, collecting the log and the tf.plan files as artifacts

**Nice to have**
![image](https://github.com/gruntwork-io/terragrunt-action/assets/803101/8f8a5033-b19a-43a7-9e81-b4ee0d44d949)
this is the end of the output from the debug step, showing that normally, jobs run as `runner` while the `.gerragrunt-cache` are owned by `root`.

**Versions**
- Terragrunt Action version: v3
- Terragrunt version 0.52.3
- Terraform version 1.6.1

**Additional context**
Perhaps all you have to do is add a user statement in the dockerfile
