### ISSUE TITLE
Add `terragrunt-actions/setup-terragrunt` Action

### ISSUE THREAD

**Issue by yordis** [gruntwork-io/terragrunt-action#32]
**Describe the solution you'd like**

I would like to have an Action that setup the tools in the given context, without doing magical things like `tg_command`

```
name: 'Terragrunt GitHub Actions'
on:
  - pull_request

env:
  tf_version: '1.4.6'
  tg_version: '0.46.3'
  working_dir: 'project'

jobs:
  terraform:
    runs-on: ubuntu-latest
    needs: [ checks ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Setup Terragrunt
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
      # .........
```

**Describe alternatives you've considered**
Use the main action that hides away the hosts environment behind the Action, forcing the steps to be owned by the action when it comes to anything related to terragrunt.
I seen this done before and end up being an anti-pattern, or requiring hacky things of passing things like SSH keys and Github Tokens to the container rather than leveraging the hosts, at least as I could expect.

**Additional context**

Most `setup-*` action exists that only inject the binaries to avoid the problems listed before.

**Comment by yordis** [comment]
Here is the existing workflow that I am trying to migrate more and less:

```yaml
name: Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - terraform/**
      - .github/workflows/terraform.yaml
      - .tool-versions
  pull_request:
    branches:
      - master
    paths:
      - terraform/**
      - .github/workflows/terraform.yaml
      - .tool-versions

env:
  TF_LOG: DEBUG
  TERRAGRUNT_NON_INTERACTIVE: true

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    env:
      tf_working_dir: terraform
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_ACCESS_KEY }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      SPACES_ACCESS_KEY_ID: ${{ secrets.DO_SPACES_ACCESS_ID }}
      SPACES_SECRET_ACCESS_KEY: ${{ secrets.DO_SPACES_ACCESS_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Get Terraform Version
        uses: straw-hat-team/github-actions-workflows/asdf/get-version@v1.6.4
        id: terraform-version
        with:
          plugin-name: terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: ${{ steps.terraform-version.outputs.plugin-version }}
          terraform_wrapper: true

      - name: Get Terragrunt Version
        uses: straw-hat-team/github-actions-workflows/asdf/get-version@v1.6.4
        id: terragrunt-version
        with:
          plugin-name: terragrunt

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: ${{ steps.terragrunt-version.outputs.plugin-version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform Format
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: terragrunt fmt -check
        working-directory: ${{ env.tf_working_dir }}

      - name: Terraform Init
        run: terragrunt run-all init -backend=true
        working-directory: ${{ env.tf_working_dir }}

      - name: Terraform Validate
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: terragrunt run-all validate
        working-directory: ${{ env.tf_working_dir }}

      - name: Terraform Plan
        if: github.ref != 'refs/heads/master' && github.event_name == 'pull_request'
        run: terragrunt run-all plan -input=false
        working-directory: ${{ env.tf_working_dir }}

      - name: Terragrunt Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terragrunt run-all apply -auto-approve -input=false
        working-directory: ${{ env.tf_working_dir }}
```
