### ISSUE TITLE
Error when redirecting tg command to file

### ISSUE THREAD

**Issue by thisurawijesekera** [gruntwork-io/terragrunt-action#40]
**Describe the bug**
Failed when trying to redirect tg command to file

**To Reproduce**
Try to redirect tg_command to a file

```
    - name: Run Terragrunt Plan Json output
      if: ${{ inputs.ACTION == 'plan' }}    
      uses: gruntwork-io/terragrunt-action@v1.0.10
      with:
        tf_version: ${{ env.TERRAFORM_VERSION }}
        tg_version: ${{ env.TERRAGRUNT_VERSION }}
        tg_dir: vars/${{ env.ENVIRONMENT }}
        tg_command: 'show -json  output.tfplan > tfplan.json'

    - name: Run Terragrunt Plan txt output 
      if: ${{ inputs.ACTION == 'plan' }}    
      uses: gruntwork-io/terragrunt-action@v1.0.10
      with:
        tf_version: ${{ env.TERRAFORM_VERSION }}
        tg_version: ${{ env.TERRAGRUNT_VERSION }}
        tg_dir: vars/${{ env.ENVIRONMENT }}
        tg_command: 'show --no-color  output.tfplan  2>&1 > tfplan.txt'
```

**Expected behavior**
Should be able to redirect to a file. Can do in locally.

**Nice to have**
- [ ] Terminal output
![image](https://github.com/gruntwork-io/terragrunt-action/assets/98374770/fffaeaf6-8cfd-416f-85c5-e54cb13f6b2c)

**Versions**
- Terragrunt Action version:  TERRAGRUNT_VERSION: 0.53.8
- Environment details (Terragrunt version, Terraform version, etc.):     TERRAFORM_VERSION: 1.6.5
