### ISSUE TITLE
Error finding AWS credentials

### ISSUE THREAD

**Issue by Giladt2789** [gruntwork-io/terragrunt-action#42]
Trying to run terragrunt apply on a code i have.
AWS CLI is configured and profile is defined. 

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```
  terraform_code:
    needs: pre-requisites
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region eu-central-1
          aws configure set default.output json
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: true
      - name: Setup Terraform version
        run: terraform --version
      - name: Setup Terraform wrapper path
        run: |
          which terraform
          pwd
      - name: Setting AWS env. vars.
        run: |
          printenv
      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: 1.5.7
          tg_version: 0.54.21
          tg_dir: /github/workspace/Terraform/
#          tg_dir: $GITHUB_WORKSPACE/Terraform/
          tg_command: 'apply'
```

**Expected behavior**

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt Action version: v2
- Environment details (Terragrunt version, Terraform version, etc.):
- terragrunt version: 0.54.21
- terraform version: 1.5.7

**Additional context**
the error as provided in the action:
```
Run gruntwork-io/terragrunt-action@v2
/usr/bin/docker run --name ee65ec3775[19](https://github.com/Giladt2789/p81/actions/runs/7681275632/job/20934296506#step:10:20)63575d48d293f14f0922bd57c7_266c52 --label ee65ec --workdir /github/workspace --rm -e "REGION" -e "STATE_FILES_BUCKET" -e "PROFILE_NAME" -e "STATEFILE_LOCK_TABLE" -e "ACCOUNT_NUMBER" -e "IAM_USER_NAME" -e "TASK_BUCKET_NAME" -e "ORIGIN_ID" -e "TERRAFORM_CLI_PATH" -e "INPUT_TF_VERSION" -e "INPUT_TG_VERSION" -e "INPUT_TG_DIR" -e "INPUT_TG_COMMAND" -e "INPUT_TG_COMMENT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/p81/p81":"/github/workspace" ee65ec:37751963575d48d293f14f0922bd57c7
[20](https://github.com/Giladt2789/p81/actions/runs/7681275632/job/20934296506#step:10:21)24-01-27 21:30:54 Starting Terragrunt Action
Installing Terraform v1.5.7
Downloading release tarball from https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip

#####                                                                      7.6%
##############                                                            20.0%
############################                                              39.9%
#############################################                             63.6%
############################################################              83.6%
######################################################################## 100.0%
Downloading SHA hash file from https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_SHA256SUMS
Not instructed to use Local PGP (/home/runner/.tfenv/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification
Archive:  /tmp/tfenv_download.4hc54V/terraform_1.5.7_linux_amd64.zip
  inflating: /home/runner/.tfenv/versions/1.5.7/terraform  
Installation of terraform v1.5.7 successful. To make this your default version, run 'tfenv use 1.5.7'
Switching default version to v1.5.7
Default version (when not overridden by .terraform-version or TFENV_TERRAFORM_VERSION) is now: 1.5.7
Terragrunt version environment variable: 0.54.[21](https://github.com/Giladt2789/p81/actions/runs/7681275632/job/20934296506#step:10:22)
20[24](https://github.com/Giladt2789/p81/actions/runs/7681275632/job/20934296506#step:10:25)/01/[27](https://github.com/Giladt2789/p81/actions/runs/7681275632/job/20934296506#step:10:28) 21:30:55 Creating directory for terragrunt: /home/runner/.terragrunt.versions/
2024/01/27 21:30:55 Creating directory for terragrunt: /home/runner/bin
Unable to write to: /usr/local/bin/terragrunt
Creating bin directory at: /home/runner/bin
RUN `export PATH=$PATH:/home/runner/bin` to append bin to $PATH
Downloading https://github.com/gruntwork-io/terragrunt/releases/download/v0.54.21/terragrunt_linux_amd64 to terragrunt_linux_amd64
Downloading ...
688[29](https://github.com/Giladt2789/p81/actions/runs/7681275632/job/20934296506#step:10:30)375 bytes downloaded.
Switched terragrunt to version "0.54.21" 
time=2024-01-27T21:[30](https://github.com/Giladt2789/p81/actions/runs/7681275632/job/20934296506#step:10:31):56Z level=error msg=Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
time=2024-01-27T21:30:56Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1
time=2024-01-27T21:30:56Z level=error msg=Suggested fixes: 
Missing AWS credentials. Provide credentials to proceed.
```

**Comment by denis256** [comment]
Hi,
try to pass credentials through `env`:

```
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-west-2'
```

**Comment by yevhen-kalyna** [comment]
I guess, its because this action running in a container and don't have access to `~/.aws/credentials`

According to output of step:
```
Run gruntwork-io/terragrunt-action@v2
/usr/bin/docker run --name asdasdas123--label abbf75 --workdir /github/workspace --rm -e "tf_version" -e "tg_version" -e "AWS_DEFAULT_REGION" -e "AWS_REGION" -e "AWS_ACCESS_KEY_ID" -e "AWS_SECRET_ACCESS_KEY" -e "AWS_SESSION_TOKEN" -e "GITHUB_TOKEN" -e "INPUT_TF_VERSION" -e "INPUT_TG_VERSION" -e "INPUT_TG_COMMAND" -e "INPUT_TG_DIR" -e "INPUT_TG_COMMENT" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_ID_TOKEN_REQUEST_URL" -e "ACTIONS_ID_TOKEN_REQUEST_TOKEN" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/REPONAME":"/github/workspace" abbf75:3c680dc150b440e3ba5b1e5dda8883b2
```

**Comment by yevhen-kalyna** [comment]
I fixed the issue by providing path to the AWS credentials file
```
      - name: Setup SSH
        shell: bash
        run: |
          # This will copy our creds to the workspace, which, GitHub will mount to the action's container
          cp -r ~/.aws .

      - name: Terragrunt Apply
        uses: gruntwork-io/terragrunt-action@v2
        env:
          # /github/workspace is path in container, aka /home/runner/workspace.. in GHA Runner
          AWS_SHARED_CREDENTIALS_FILE: /github/workspace/.aws/credentials
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_command: run-all apply
          tg_dir: ${{ matrix.folder }}
```

**Comment by yiskaneto** [comment]
> **To Reproduce**
> Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue

Hey just a tip, instead of using fixed access and secret keys you can use dynamically generated keys that only last for the run of the action, this reduces the risk of leaking keys and manage of them. This is achieved by using OIDC, see https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

**Comment by yiskaneto** [comment]
> I fixed the issue by providing path to the AWS credentials file
> 
> ```
>       - name: Setup SSH
>         shell: bash
>         run: |
>           # This will copy our creds to the workspace, which, GitHub will mount to the action's container
>           cp -r ~/.aws .
> 
>       - name: Terragrunt Apply
>         uses: gruntwork-io/terragrunt-action@v2
>         env:
>           # /github/workspace is path in container, aka /home/runner/workspace.. in GHA Runner
>           AWS_SHARED_CREDENTIALS_FILE: /github/workspace/.aws/credentials
>         with:
>           tf_version: ${{ env.tf_version }}
>           tg_version: ${{ env.tg_version }}
>           tg_command: run-all apply
>           tg_dir: ${{ matrix.folder }}
> ```

Hey just a tip, instead of using fixed access and secret keys you can use dynamically generated keys that only last for the run of the action, this reduces the risk of leaking keys and manage of them. This is achieved by using OIDC, see https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

**Comment by nischalstha9** [comment]
Tried passing env variable to container for using OIDC which didn't worked.
```yml
  - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        env:
          AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          AWS_SESSION_TOKEN: $AWS_SESSION_TOKEN
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "plan"

```
So, did a workaround as of @yevhen-kalyna 

```yml


      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GH-Actions-${{ github.run_id }}-${{ github.run_attempt }}
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}

      - name: Setup
        shell: bash
        run: |
          mkdir -p .aws
          cat >> .aws/credentials << EOF
          [default]
          aws_access_key_id = $AWS_ACCESS_KEY_ID
          aws_secret_access_key = $AWS_SECRET_ACCESS_KEY
          aws_session_token = $AWS_SESSION_TOKEN
          EOF

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2
        env:
          AWS_SHARED_CREDENTIALS_FILE: /github/workspace/.aws/credentials
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: "plan"
```
