### ISSUE TITLE
Error when apply from specific plan file

### ISSUE THREAD

**Issue by spchortis** [gruntwork-io/terragrunt-action#43]
**Describe the bug**
Failed to execute TG apply from a plan file that was previously created

**To Reproduce**
When creating a pipeline with the code below.

```
        - name: Plan
          uses: gruntwork-io/terragrunt-action@v2
          with:
            tf_version: ${{ env.tf_version }}
            tg_version: ${{ env.tg_version }}
            tg_dir: "${{ env.working_dir }}/${{ inputs.environment }}"
            tg_command: 'run-all plan -out tfplan-${{ inputs.environment }}'
  
        - name: Apply
          uses: gruntwork-io/terragrunt-action@v2
          with:
            tf_version: ${{ env.tf_version }}
            tg_version: ${{ env.tg_version }}
            tg_dir: "${{ env.working_dir }}/${{ inputs.environment }}"
            tg_command: 'run-all apply tfplan-${{ inputs.environment }}'
```

**Expected behavior**
We expect run-all apply to be able to run from a plan file that was previously created. Works locally. 

**Nice to have**
- [ ] Terminal output
![Screenshot_20240202_090653](https://github.com/gruntwork-io/terragrunt-action/assets/86228064/03abadd1-e559-4bc0-9d3a-4bcc10a0f90e)

**Versions**
- Terragrunt Action version: v2
- Terragrunt version: 0.46.3, Terraform version: 1.4.7
