### ISSUE TITLE
Action asking for input

### ISSUE THREAD

**Issue by adhuber** [gruntwork-io/terragrunt-action#47]
**Describe the bug**

Action fails to apply and run non-interactively

**To Reproduce**
Use action with version >= 2.0.1
```
uses: gruntwork-io/terragrunt-action@v2.0.1
        with:
          tf_version: 1.6.5
          tg_version: 0.53.8
          tg_dir: terraform
          tg_command: >-
            apply
            --var-file devl.tfvars
```

**Expected behavior**
Action does not ask for input

**Nice to have**
Terminal ouput:
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: ╷
│ Error: error asking for approval: EOF
│ 
│ 
╵
```

**Versions**

- Terragrunt Action version: v2.0.1
tf_version: 1.6.5
tg_version: 0.53.8
