### ISSUE TITLE
Terragrunt not available after action

### ISSUE THREAD

**Issue by J4NS-R** [gruntwork-io/terragrunt-action#57]
**Describe the bug**
After the action completes, the `terragrunt` executable is no longer available.

Is the terragrunt installation cleaned after the action? Is there a way to disable this?

**To Reproduce**

```yaml
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Terragrunt action
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: "1.7.5"
          tg_version: "0.56.2"
          tg_dir: "."
          tg_command: '--version'
          tg_add_approve: 0
          tg_comment: 0
        env:
          INPUT_POST_EXEC_1: which terragrunt
      - name: Terragrunt checks
        run: /home/runner/bin/terragrunt hclfmt --terragrunt-check --terragrunt-diff
```

**Expected behavior**

The steps following the initial action can execute `terragrunt`. If not on the `$PATH`, then at least still available in its bin directory.

**Screenshot**

![image](https://github.com/gruntwork-io/terragrunt-action/assets/14095706/4ab73e1d-5c7e-4064-b2e3-29449615a2fd)

➡️ Notice that the output of `which terragrunt` is `/home/runner/bin/terragrunt`, but trying to execute this path directly fails with "No such file or directory".

**Versions**
- Terragrunt Action version: `v2`
- Environment details: See action yaml above
