### ISSUE TITLE
tg_add_approve seems to be ignored when running run-all apply

### ISSUE THREAD

**Issue by paololazzari** [gruntwork-io/terragrunt-action#62]
Here's the step:

```
- name: Run apply
  uses: gruntwork-io/terragrunt-action@v2
  with:
    tf_version: '1.5.7'
    tg_version: '0.53.2'
    tg_dir: "${{ github.event.inputs.environment }}/"
    tg_command: 'run-all apply'
    tg_add_approve: 0
```

yet the workflow still auto-approves
