### ISSUE TITLE
Host key verification failed after update to 2.1.1

### ISSUE THREAD

**Issue by asveepay** [gruntwork-io/terragrunt-action#63]
**Describe the bug**
Something about #61 and the subsequent upgrade of the terragrunt base image appears to have broken `SSH_AUTH_SOCK` compatibility when using the webfactory/ssh-agent github action to provide an ssh key for cloning a private repo.

**To Reproduce**
Our setup is like so and has been working great up until today (2024-05-02)

```
      - name: create directory to pass ssh-agent socket
        run: "mkdir -p /home/runner/work/_temp/_github_workflow"
        shell: bash

     - name: Set SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-auth-sock: "/home/runner/work/_temp/_github_workflow/ssh-agent.sock"

      - name: Deploy to ${{ inputs.environment }}
        uses: gruntwork-io/terragrunt-action@v2.1.0
        env:
          SSH_AUTH_SOCK: "/github/workflow/ssh-agent.sock"
          TAG: ${{ inputs.release_tag }}
          AWS_ACCESS_KEY_ID: ${{ steps.creds.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY: ${{ steps.creds.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN: ${{ steps.creds.outputs.aws-session-token }}
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        with:
          tf_version: ${{ env.TERRAFORM_VERSION }}
          tg_version: ${{ env.TERRAGRUNT_VERSION }}
          tg_dir: deploy/${{ env.RAILS_ENV }}
          tg_command: 'apply'
```

The error message received from the first build using version `2.1.1` of the github action:
```
time=2024-05-02T20:02:17Z level=error msg=1 error occurred:
	* error downloading 'ssh://git@github.com/org/infrastructure.git?ref=1.0.97': /usr/bin/git exited with 128: Cloning into '/github/workspace/deploy/staging/.terragrunt-cache/53Hsb859eOwkuzty3PW9lw9U5fY/hw3uw5AmWDBEWfvkFdRXrR0Gjwo'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Github action build info for previous successful deployment:**
![successful_build](https://github.com/gruntwork-io/terragrunt-action/assets/677892/99c43d84-d2b7-4d8e-b8c2-7682dabe5f1c)

**Github action build info for next unsuccessful deployment:**
![unsuccessful_build](https://github.com/gruntwork-io/terragrunt-action/assets/677892/ec86fa6b-9120-4df1-af54-79c895f511e5)

**Expected behavior**

Expected that the `infrastructure` repo can be cloned successfully while terragrunt runs.

I was able to work around this issue by pinning the action to version 2.1.0.

**Versions**
- Terragrunt Action version: 2.1.1
- Environment details (Terragrunt version, Terraform version, etc.): Terragrunt version 0.39.0, Terraform version 1.3.1
