### ISSUE TITLE
2.1.1 file permissions changed after terragrunt actions runs

### ISSUE THREAD

**Issue by kramuenke** [gruntwork-io/terragrunt-action#64]
**Describe the bug**

Hi all. We use the terragrunt action in combination with `google-github-actions/auth@v2`. Since today all our deployments are failing when `google-github-actions/auth@v2` tries to delete its temporary credentials file.

![Screenshot 2024-05-03 at 3 22 42 PM](https://github.com/gruntwork-io/terragrunt-action/assets/469886/6ca18aac-096e-4ad3-b171-b02f64e20bf0)

When removing the terragrunt step from the workflow the post step for `google-github-actions/auth@v2` cleans up fine. This may be a similar issue to https://github.com/gruntwork-io/terragrunt-action/issues/60 which also reports file permission issues for post cleanup steps

We tried downgrading and pin to previous versions (v2.1.0 and v2.0.2) but the file permission issue still persists.

We see this issue on self-hosted runners and github ubuntu runners

**To Reproduce**

Reproduce by using a workflow like

```
name: Staging Deploy

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: blacksmith-2vcpu-ubuntu-2204
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: '<an identiry>'
          service_account: '<some service-account>'
      - name: Setup GCloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: <some project id>
      - uses: rlespinasse/github-slug-action@v4
        with:
          short-length: 7
      - name: Deploy
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: '1.7.4'
          tg_version: '0.55.1'
          tg_dir: ./ops/terragrunt/environments/staging/app-port
          tg_command: 'apply'
```

Running the same workflow without `Deploy` step has no issues on Post step for `google-github-actions/auth`

**Expected behavior**

**Nice to have**
- [ ] Terminal output
- [ ] Screenshots

**Versions**
- Terragrunt Action version: 2.x
- Environment details (Terragrunt version, Terraform version, etc.):

**Additional context**

**Comment by kramuenke** [comment]
> We see this issue on self-hosted runners and github ubuntu runners

Correction: we see this only on self-hosted runners. We are using https://blacksmith.sh/

**Comment by kramuenke** [comment]
Some additional info:

The combination of pinning to `gruntwork-io/terragrunt-action@v2.0.2` and using `ubuntu-22.04` worked for now but using `gruntwork-io/terragrunt-action@v2` with `ubuntu-22.04` does not.

**Comment by fe-ax** [comment]
I noticed the following warning:

```
Failed to remove 'http.https://github.com/.extraheader' from the git config
```

And worked around the issue by adding the following `INPUT_POST_EXEC_1`:

```
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2.1.1
        env:
          AWS_CONFIG_FILE: /github/workspace/tmp/aws-config
          TF_PLUGIN_CACHE_DIR: /github/workspace/.terraform.d/plugin-cache
          TERRAGRUNT_PROVIDER_CACHE_DIR: /github/workspace/.terragrunt-cache
          INPUT_POST_EXEC_1: |
            chown -R 1001:127 .
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: "."
          tg_command: 'run-all plan -out=out.tfplan'
```
