### ISSUE TITLE
V1.0.2 Failing with  /action/main.sh: line 92: : invalid variable name

### ISSUE THREAD

**Issue by rwoodford-nex** [gruntwork-io/terragrunt-action#7]
**Describe the bug**
V1.0.2 step fails with error, reverting to V1.0.1 step is successful 

```
 2023-07-20 22:18:54 Evaluating 
/action/main.sh: line 92: : invalid variable name
2023-07-20 22:18:54 Finished Terragrunt Action execution 
```

**To Reproduce**
Steps to reproduce the behavior, code snippets and examples which can be used to reproduce the issue.

```
name: 'Validate PR'
on:
  - pull_request
  - workflow_dispatch

env:
  tf_version: '1.5.3'
  tg_version: '0.48.0'
  working_dir: 'environments'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v1
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
```

**Expected behavior**

**Versions**
- Terragrunt Action version:
- Environment details (Terragrunt version, Terraform version, etc.):

  tf_version: '1.5.3'
  tg_version: '0.48.0'

**Additional context**
