### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by kallrath** [gruntwork-io/terragrunt-action#70]
**Describe the bug**
In the Post Checkout step the following error occurs: 
`Error: Access to the path '/home/runner/work/_temp/_github_workflow/event.json' is denied.`
It only occurs in the newest version 2.1.3. The same code works with versions 2.1.1 and older. 

**To Reproduce**

```
name: 'Terragrunt GitHub Actions'
on:
  - push

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: '../..'

permissions: write-all

jobs:
  check_directory:
    runs-on: ubuntu-latest
    steps:
      - name: Set execute permissions
        run: chmod +x /home/runner/work/_temp/_github_workflow
      - name: check directory
        run: ls -la /home/runner/work/_temp/_github_workflow/
      - name: who
        run: |
          whoami
          echo "User: $(id -nu $UID)"
          echo "GID: $GID"

  checks:
    runs-on: ubuntu-latest
    needs: [ check_directory ]
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Check terragrunt HCL
        uses: gruntwork-io/terragrunt-action@v2.1.3
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'

  plan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2.1.3
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan'
```

![image](https://github.com/gruntwork-io/terragrunt-action/assets/166711449/4c388764-ded7-4316-b746-bdb7ea6fef92)

**Versions**
- Terragrunt Action version: 2.1.3
