### ISSUE TITLE
`fork/exec $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh: no such file or directory`

### ISSUE THREAD

**Issue by LittleWat** [gruntwork-io/terragrunt-action#79]
**Describe the bug**
Unfortunately, terragrunt does not catch the `tofu error`. This is quite annoying when debugging the terraform codes.

Based on https://community.gruntwork.io/t/how-to-process-terraform-apply-logs-for-catching-errors-in-ci/656/4 ,

I prepared the wrapper shell

- `.github/scripts/tfwrapper.sh`

```sh
#!/bin/bash

tofu "$@" 2>&1 | tee ./terraform.log
```

and set the github workflow as follows:

```yaml
- name: Apply
  uses: gruntwork-io/terragrunt-action@cf355638dbd066b6a70eb01f31ad9293870a0e34 # v2.1.4
  with:
    tofu_version: ${{ env.TOFU_VERSION }}
    tg_version: ${{ env.TG_VERSION }}
    tg_dir: ${{ env.WORK_DIR }}
    # to catch the error of "tofu apply" based on https://github.com/gruntwork-io/terragrunt/issues/74#issuecomment-471082576
    tg_command: 'run-all apply --terragrunt-tfpath $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh'
```

However, it fails with `fork/exec $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh: no such file or directory`

I tried the following `INPUT_PRE_EXEC_1` and it could `cat` as expected.
```yaml
     - name: Apply
        env:
          INPUT_PRE_EXEC_1: |
            cat $GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh
```

so I'm wondering how to fix this error.

**Expected behavior**

It should find `$GITHUB_WORKSPACE/.github/scripts/tfwrapper.sh`

**Versions**
- Terragrunt Action version: # v2.1.4
- Environment details (Terragrunt version, Terraform version, etc.):
  - TOFU_VERSION: 1.8.1
  - TG_VERSION: 0.67.2

**Additional context**

I want tofu apply errors to be caught by default (same https://community.gruntwork.io/t/how-to-process-terraform-apply-logs-for-catching-errors-in-ci/656 )

Currently, it just logs unuseful outputs like the following:

```log
04:57:17.253 ERROR  [kafka_admin_ec2] tofu invocation failed in /github/workspace/<path>/.terragrunt-cache/pBa95-l1_fpzkMhLdl_auz2P1_s/vxdbUoFBPPcfo8ey7QUdnvPtOeY/terraform/<module> error=[/github/workspace/terragrunt/dev/kafka_admin_ec2/.terragrunt-cache/pBa95-l1_fpzkMhLdl_auz2P1_s/vxdbUoFBPPcfo8ey7QUdnvPtOeY/terraform/<module>] exit status 1
04:57:17.253 ERROR  [<module>] Module <module> has finished with an error: 1 error occurred:
	* [/github/workspace/terragrunt/dev/<module>/.terragrunt-cache/pBa95-l1_fpzkMhLdl_auz2P1_s/vxdbUoFBPPcfo8ey7QUdnvPtOeY/terraform/<module>] exit status 1
```
and it's quite hard to debug.
