### ISSUE TITLE
PATH is different when running external_data

### ISSUE THREAD

**Issue by antspy** [gruntwork-io/terragrunt-action#84]
**Describe the bug**

I am running terragrunt using github actions. In my `.tf` file I have a `data external` piece of code which is meant to run a bash script using the `gcloud` cli. This works fine locally but not when using terragrunt action.

Code: 

```yaml
      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"

      - name: Call terragrunt apply
        uses: gruntwork-io/terragrunt-action@v2
        env:
          GOOGLE_OAUTH_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
        with:
          tf_version: "1.10.0"
          tg_version: "0.69.13"
          tg_dir: 'xxx'
          # We keep the trace log level here, so if something goes wrong we can
          # debug.
          tg_command: 'apply --terragrunt-log-level trace --terragrunt-debug'
```

My tf file contains this line: 

```tf
data "external" "my_external_data" {
  program = [
    "${var.repo_root}/src/myscript.sh",
    arg0, arg1
  ]
}
```

where `myscript` uses the `gcloud` cli. Turns out that the script cannot find the `gcloud` cli when executed through terragrunt action, because the `PATH` is completely different than what github actions normally has, and specifically it cannot find the `gcloud` cli. The `PATH` when running script through `my_external_data` contains `usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin` and a couple of other paths specific to terraform / terragrunt, but `gcloud` is installed elsewhere, and it seems that the default github actions `PATH` is ignored. 

I wanted to ask: 
1. If we could document this behavior - I spent many many hours debugging it at this point :)
2. Why this behavior exists in the first place - it seems really hard to debug. Shouldn't we aim for consistency in the execution environment ?
3. How to fix this? How do I add things to the path? 

Perhaps the best option would be to just install the `terragrunt` cli in a separate github action step, and then call `terragrunt` myself - this will ensure a consistent dev environment, and avoid this really quite hard to debug issues. 

Would be happy for any help here. 
Thanks!
