### ISSUE TITLE
INPUT_POST_EXEC_number in conjunction with tg_comment should print a comment regardless of the exit errorlevel

### ISSUE THREAD

**Issue by v1v** [gruntwork-io/terragrunt-action#96]
**Describe the solution you'd like**

When using `INPUT_POST_EXEC_number` and `tg_comment: 1` if the script at `INPUT_POST_EXEC_number` fails, no output is added to the comment.

However, I'd like to see the comment there.

For instance, I use the below step:

```
      - name: Plan
        if: github.event_name == 'pull_request'
        uses: gruntwork-io/terragrunt-action@aee21a7df999be8b471c2a8564c6cd853cb674e1 # v2.1.8
        with:
          tg_command: 'run-all plan -out=.tfplan -input=false'
          tg_comment: 1
        env:
          INPUT_POST_EXEC_1: .github/validate.sh
```

`.github/validate.sh` runs some policy enforcement detectation so I know I can run it for only the approval list of Terraform Resources.

**Describe alternatives you've considered**

Run twice

```
      - name: Plan
        if: github.event_name == 'pull_request'
        uses: gruntwork-io/terragrunt-action@aee21a7df999be8b471c2a8564c6cd853cb674e1 # v2.1.8
        with:
          tg_command: 'run-all plan'
          tg_comment: 1

      - name: Validate
        if: github.event_name == 'pull_request'
        uses: gruntwork-io/terragrunt-action@aee21a7df999be8b471c2a8564c6cd853cb674e1 # v2.1.8
        with:
          tg_command: 'run-all plan -out=.tfplan -input=false'
          tg_comment: 1
        env:
          INPUT_POST_EXEC_1: .github/validate.sh
```

**Additional context**

<img width="1314" alt="Image" src="https://github.com/user-attachments/assets/a5e3f80f-d772-4dd4-87d9-7bca432b9e75" />
